version: 2.1

orbs:
  sdk: ory/sdk@0.1.23
  changelog: ory/changelog@0.0.6
  goreleaser: ory/goreleaser@0.0.27
  nancy: ory/nancy@0.0.8

jobs:
  format:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ory/keto
    steps:
      - checkout
      - run:
          name: Enable go1.11 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
      - run: go mod download
      - run: golangci-lint run ./...

  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          - TEST_DATABASE_POSTGRESQL=postgres://test:test@localhost:5432/keto?sslmode=disable
          - TEST_DATABASE_MYSQL=root:test@(localhost:3306)/mysql?parseTime=true
      - image: postgres:9.5
        environment:
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
          - POSTGRES_DB=keto
      - image: mysql:8.0
        environment:
          - MYSQL_ROOT_PASSWORD=test
    working_directory: /go/src/github.com/ory/keto
    steps:
      - checkout
      - setup_remote_docker
      # Installation
      - run: go mod verify
      - run: go install github.com/ory/keto
      - run: go install github.com/go-swagger/go-swagger/cmd/swagger github.com/bradfitz/goimports github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/ory/go-acc

      # Tests
      - run: go test -race -short -v $(go list ./... | grep -v cmd)
      - run: go-acc -v -o coverage.txt ./...
      - run: ./scripts/test-e2e.sh

      # Submit coverage details
      - run: test -z "$CIRCLE_PR_NUMBER" && goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN || echo "forks are not allowed to push to coveralls"

workflows:
  version: 2
  "test, build, and relase":
    jobs:
      - nancy/test:
          filters:
            tags:
              only: /.*/
      - format:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - changelog/generate:
          requires:
            - test
            - format
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - sdk/generate:
          appname: Ory_Keto
          swagpath: contrib/api.schema.json
          requires:
            - test
            - format
      - sdk/release:
          swagpath: contrib/api.schema.json
          requires:
            - test
            - format
            - goreleaser/release
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - goreleaser/test:
          filters:
            tags:
              only: /.*/
      - goreleaser/release:
          requires:
            - goreleaser/test
            - test
            - format
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
